[build]
  publish = "."
  command = ""
  environment = { NODE_VERSION = "16" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
