services:
  - type: web
    name: controle-despesas-backend
    env: node
    region: oregon # Você pode mudar para uma região mais próxima do Brasil
    buildCommand: ls -la && npm install && ls -la && mkdir -p backend && cd backend && npm install
    startCommand: node start.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: RENDER
        value: "true"
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
