services:
  - type: web
    name: controle-despesas-backend
    env: node
    region: oregon # Você pode mudar para uma região mais próxima do Brasil
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start:render
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 1
